# Third-party services
[services]

    # Discord settings
    [services.discord]

        # Authentication token for the discord bot
        # Get one at: https://discordapp.com/developers/applications/
        bot-token = 'YOUR_BOT_TOKEN'

        # Home guild id of the bot
        # The bot will leave all other guilds on login
        home-guild = '600328651124506625'

        # Owners of the bot
        # Note: in debug mode the bot will only listen to the users defined below
        owner = ['319083113235873793', '561134116716806155']